Задание №1
vasilenko/bering pull request #1
Opened 2017-05-26 11:50 UTC by vasilenko

2017-05-27 08:17 UTC, index01d requested changes
Есть замечания

2017-05-27 08:17 UTC, index01d commented on components/BlogItem.js
> +    {Image(image)}
Лучше создать элемент, Просто вызов функции в данном случае сработал, но есть ряд нюансов с отсутствием у такого экземпляра жизненного цикла элемента компонента

2017-05-27 08:17 UTC, index01d commented on components/BlogItem.js
> +    {Image(image)}
должно быть `<Image ...тут свойства также как и для компонента-класса>`

2017-05-27 08:17 UTC, index01d commented on components/BlogList.js
> +      <BlogItem key={key} text={el.text} image={el.image} />
лучше компоненту отображения записи передавать всю запись целиком без деструктурирования. В качестве ключа лучше использовать уникальный идентификатор el.id (завести его в исходном массиве записей)

2017-05-29 10:05 UTC, blackleadsu approved these changes
Замечания исправлены, всё в порядке

2017-05-29 10:07 UTC, merged