Task 6
vasilenko/bering pull request #6
Opened 2017-07-25 15:16 UTC by vasilenko

2017-07-26 06:38 UTC, index01d requested changes

2017-07-26 06:38 UTC, index01d commented on src/actions/Post.js
> +          // Reload all posts for simplicity
неправильно, достаточно создать action LIKE_SUCCESS и обработать его в reducer'aх постов. Тогда запрос на `/like` должен будет возвращать только итоговое количество лайков

2017-07-26 06:38 UTC, index01d commented on src/components/containers/PostPage.js
> +const stateToPostPageProps = (state) => ({
избыточное название. Принято просто stateToProps

2017-07-26 06:38 UTC, index01d commented on src/components/containers/PostPage.js
> +const dispatchToBlogItemProps = (dispatch) => ({
Избыточное название

2017-07-26 06:38 UTC, index01d commented on src/components/containers/PostPage.js
> +const WrappedBlogItem = connect(stateToBlogItemProps, dispatchToBlogItemProps)(BlogItem);
Должен быть отдельный контейнер. Тогда не понадобится промежуточная константа и модуль будет экспортировать по-умолчанию

2017-07-26 06:38 UTC, index01d commented on src/components/containers/PostPage.js
>  import React from 'react';
не стоит перемешивать два контейнера в одном

2017-07-26 06:38 UTC, index01d commented on src/components/containers/PostPage.js
> +import { Item, Dimmer, Loader } from 'semantic-ui-react';
не должно быть презентационной логики в контейнерном компоненте и контейнерной логики в презентационном

2017-07-26 06:38 UTC, index01d commented on src/components/containers/BlogPage.js
> +const WrappedPieChart = connect(stateToPieChartProps)(BlogPieChart);
нужен отдельный контейнер

2017-07-26 06:38 UTC, index01d commented on src/components/containers/BlogPage.js
> +const WrappedBlogList = connect(stateToBlogListProps, dispatchToBlogListProps)(BlogList);
нужен отдельный контейнер

2017-07-26 06:38 UTC, index01d commented on src/components/containers/BlogPage.js
> +const stateToBlogListProps = (state) => ({
избыточное название

2017-07-26 06:38 UTC, index01d commented on src/components/containers/BlogPage.js
> +const dispatchToBlogListProps = (dispatch) => ({
избыточное название

2017-07-26 06:38 UTC, index01d commented on src/components/containers/BlogPage.js
> +  incrementLikeCount: (id) => dispatch(likePost(id))
метод для инкремента лайка должен быть в контейнере Like'a (LikeContainer можно создать, например)

2017-07-26 06:38 UTC, index01d commented on src/App.js
> +const history = createBrowserHistory(Router);
обрати внимание на замечание здесь: http://connect.thinknetica.com/t/sergej-drogan-drawgun/4594/50?u=indevelope

2017-07-26 06:40 UTC, index01d commented on src/components/containers/BlogPage.js
> +  incrementLikeCount: (id) => dispatch(likePost(id))
я имею ввиду примерно следующую схему (на примере кода другого ученика):

В LikeContainer реализовать redux-container:

```
import { get, find, flowRight } from 'lodash';

import Like from 'components/ui/Like';
import { addLike } from 'actions/Like';

...
const stateToProps = (state, ownProps) => ({
  amount: get(
    find(state.posts.items, { id: ownProps.itemId }), 
    'likes', 
    get(state, 'post.item.likes', 0)
  )
});

const actionsToProps = (dispatch, ownProps) => (
  addLike: () => dispatch(addLike(ownProps.itemId))
);

export default connect(stateToProps, actionsToProps)(Like);
```

Презентационный компонент станет таким

```
import React from 'react';
import Button from 'react-mdl/lib/Button';


const Likes = ({addLike, amount}) =>{

    return(
        <Button onClick={()=> addLike()}
             style={{border: '1px solid green',
             width: 'auto',
             cursor: 'pointer'}}>
            {`likes: ${amount}`}
        </Button>
    )
};


Like.propTypes = {
    amount: React.PropTypes.number.isRequired,
    addLike: React.PropTypes.func.isRequired
};

export default Like;
```

В BlogItem использовать его следующим образом

```
import LikeContainer from 'containers/LikeContainer';
...
<LikeContainer itemId={item.id} /> // здесь разумеется рендерить с условием, только когда item.id уже есть
```

2017-07-26 07:10 UTC, vasilenko commented on src/App.js
> +const history = createBrowserHistory(Router);
Отлично. Спасибо.

2017-07-26 13:54 UTC, vasilenko commented on src/components/containers/BlogPage.js
> +  incrementLikeCount: (id) => dispatch(likePost(id))
Проблема в том, что актуальное число лайков хорошо бы положить в и `state.posts.entries`, и в `state.post.entry`, т.к. кнопки лайка присутствуют на обоих страницах.

Диспачить два разных события? Или лучше переделать способ сохранения поста в стор? Мне кажется разумной идея хранить посты в одном месте вроде `state.posts.entries = { id_поста: пост, … }`

2017-07-28 12:12 UTC, index01d requested changes
Оставил дополнительные замечания

2017-07-28 12:12 UTC, index01d commented on src/components/BlogPage.js
> +  const chartData = posts.map((post) =>
контейнерная логика. Лучше выделить PieChartContainer и расчитать это там из единого состояния

2017-07-28 12:12 UTC, index01d commented on src/components/BlogPage.js
> +          <BlogPieChart data={chartData} />
тогда здесь будет использоваться `<PieChartContainer />`

2017-07-28 12:12 UTC, index01d commented on src/components/PostPage.js
> +  if (isFetching) {
по желанию можно сделать Loader в виде HOC-компонента withLoader(), получится что-то типа
```
export const withLoader = (Component) => (props) => (
  props.error ? 
    <NotFoundPage />
    : props.isFetching ?
      <Loading />
      : <Component {...props} />
);

const Loading = () => (
  <Dimmer active inverted>
    <Loader inverted>Loading</Loader>
  </Dimmer>
);
```

и на месте использовать его как `import { withLoader } from 'components/HOCs/withLoader'` и потом `export default withLoader(PostPage)` например. Тогда не придется делать дублирование кода

2017-07-28 12:12 UTC, index01d commented on src/components/PostPage.js
> +      <BlogItem post={post} incrementLikeCount={incrementLikeCount} />
чтобы не пробрасывать экшен по длинной иерархии, можно создать LikeContainer и использовать его на месте

2017-07-28 12:53 UTC, vasilenko commented on src/components/PostPage.js
> +      <BlogItem post={post} incrementLikeCount={incrementLikeCount} />
Ох. Забыл удалить.

2017-07-28 13:55 UTC, vasilenko commented on src/components/PostPage.js
> +  if (isFetching) {
Какая крутота. Спасибо.

2017-07-29 07:43 UTC, index01d approved these changes

2017-07-29 08:13 UTC, merged